### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by fischejo** [argos-research/taskgen#5]
Milestone: v1.1
```
@type
Exception in thread Thread-22:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/home/fischejo/university/informatik/in2261-bachelor/bsc-taskgen/toolchain-host/taskgen/distributor.py", line 484, in run
    if not self._internal_update_handling(session):
  File "/home/fischejo/university/informatik/in2261-bachelor/bsc-taskgen/toolchain-host/taskgen/distributor.py", line 445, in _internal_update_handling
    taskset_changed = session.run(self._taskset)
  File "/home/fischejo/university/informatik/in2261-bachelor/bsc-taskgen/toolchain-host/taskgen/sessions/genode.py", line 126, in run
    _task_id = int(event['@task-id'])
TypeError: string indices must be integers
```

**Comment by fischejo** [comment]
solved by #12
